2025-03-23 10:38:47,271 - DEBUG - Entre to the function.
2025-03-23 10:38:47,272 - DEBUG - Starting new HTTPS connection (1): jsonplaceholder.typicode.com:443
2025-03-23 10:38:47,957 - DEBUG - https://jsonplaceholder.typicode.com:443 "GET /posts/fdfg34 HTTP/1.1" 404 2
2025-03-23 10:38:47,957 - ERROR - 404 Client Error: Not Found for url: https://jsonplaceholder.typicode.com/posts/fdfg34
Traceback (most recent call last):
  File "/home/renepro/Renecito/Python/Curso_Cepi/sesion_1/apis/deco_loggi.py", line 22, in warpper
    result = func(*args,**kwargs)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/renepro/Renecito/Python/Curso_Cepi/sesion_1/apis/main.py", line 12, in get_data_users
    response.raise_for_status()
  File "/home/renepro/Renecito/Python/Curso_Cepi/sesion_1/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://jsonplaceholder.typicode.com/posts/fdfg34
